<?php

$_COS_LANG_MODULE['module_system_git_menu_user_list'] = 'Liste dine moduler';
$_COS_LANG_MODULE['module_system_git_menu_add'] = 'Tilføj ny Module';
$_COS_LANG_MODULE['module_system_git_menu_admin_list'] = 'Skjulte moduler';
$_COS_LANG_MODULE['Modules'] = 'Moduler';
$_COS_LANG_MODULE['module_system_git_menu_list'] = 'List Modules';
$_COS_LANG_MODULE['module_system_git_menu_user'] = 'Dine moduler';
$_COS_LANG_MODULE['module_system_git_menu_admin'] = 'Admin';
