<?php

$_COS_LANG_MODULE['module_system_git_menu_user_list'] = '列出您的模块';
$_COS_LANG_MODULE['module_system_git_menu_add'] = '添加新模块';
$_COS_LANG_MODULE['module_system_git_menu_admin_list'] = '隐藏模块';
$_COS_LANG_MODULE['Modules'] = '模块';
$_COS_LANG_MODULE['module_system_git_menu_list'] = '列表模块';
$_COS_LANG_MODULE['module_system_git_menu_user'] = '您的模块';
$_COS_LANG_MODULE['module_system_git_menu_admin'] = '管理员';
