<?php

// Translation of file /home/dennis/www/coscms/modules/module_system_git/view.module_system_git.inc

$_COS_LANG_MODULE['Show All'] = 'Show All';
$_COS_LANG_MODULE['Search'] = 'Search';
$_COS_LANG_MODULE['module_system_git_edit'] = 'Edit';
$_COS_LANG_MODULE['module_system_git_delete'] = 'Delete';
$_COS_LANG_MODULE['module_system_git_install'] = 'Install';
// Translation of file /home/dennis/www/coscms/modules/module_system_git/model.module_system_git.inc

$_COS_LANG_MODULE['module_system_git_form_title'] = 'Title. Must be unique';
$_COS_LANG_MODULE['module_system_git_form_abstract'] = 'Write an abstract (you can use <a href="http://daringfireball.net/projects/markdown/syntax">markdown syntax</a>)';
$_COS_LANG_MODULE['module_system_git_form_url'] = 'Enter a url with more info about module';
$_COS_LANG_MODULE['module_system_git_form_clone_url'] = 'Enter a public clone url';
$_COS_LANG_MODULE['module_system_git_form_type'] = 'Type of module: Module, Template or Profile';
$_COS_LANG_MODULE['Delete Module'] = 'Delete Module';
$_COS_LANG_MODULE['Edit Module'] = 'Edit Module';
$_COS_LANG_MODULE['Add Module'] = 'Add Module';
$_COS_LANG_MODULE['module_system_git_error_title'] = 'Not a valid title. Needs to be at least 7 chars';
$_COS_LANG_MODULE['module_system_git_error_title_exists'] = 'Title exists';
$_COS_LANG_MODULE['module_system_git_error_abstract'] = 'Please supply a short abstract';
$_COS_LANG_MODULE['module_system_git_error_url'] = 'Not a valid url';
$_COS_LANG_MODULE['module_system_git_error_url_exists'] = 'Url already exists';
$_COS_LANG_MODULE['module_system_git_error_clone_url'] = 'Not a valid clone url';
$_COS_LANG_MODULE['module_system_git_error_clone_url_exists'] = 'Clone url already exists';
$_COS_LANG_MODULE['module_system_git_error_clone_url_no_tag'] = 'Your module need at least one tag';
$_COS_LANG_MODULE['module_system_git_error_clone_url_tag_not_float'] = 'Your module needs to use floats as version tags';
// Translation of file /home/dennis/www/coscms/modules/module_system_git/user/add.php

$_COS_LANG_MODULE['module_system_git_module_created'] = 'Module has been created. Your module will be ativated when it has been verfied - you will recieve an email';
// Translation of file /home/dennis/www/coscms/modules/module_system_git/user/delete.php

$_COS_LANG_MODULE['module_system_git_delete_module'] = 'Delete_Module';
$_COS_LANG_MODULE['module_system_git_module_deleted'] = 'Module Deleted';
// Translation of file /home/dennis/www/coscms/modules/module_system_git/user/edit.php

$_COS_LANG_MODULE['module_system_git_module_updated'] = 'Module Updated';


$_COS_LANG_MODULE['module_system_git_read_more'] = '(More info)';
$_COS_LANG_MODULE['module_system_git_visit_website'] = 'Website';


$_COS_LANG_MODULE['module_system_git_hide'] = 'Hide';
$_COS_LANG_MODULE['module_system_git_show'] = 'Show';
