<?php


// Translation of file /modules/module_system_git/admin/menu.inc

$_COS_LANG_MODULE['module_system_git_menu_admin_list'] = 'Hidden Modules';

// Translation of file /modules/module_system_git/install.inc

$_COS_LANG_MODULE['Modules'] = 'Modules';

// Translation of file /modules/module_system_git/user/menu.inc

$_COS_LANG_MODULE['module_system_git_menu_user_list'] = 'List Your Modules';
$_COS_LANG_MODULE['module_system_git_menu_add'] = 'Add New Module';

// Translation of file /modules/module_system_git/menu.inc

$_COS_LANG_MODULE['module_system_git_menu_list'] = 'List Modules';
$_COS_LANG_MODULE['module_system_git_menu_user'] = 'Your Modules';
$_COS_LANG_MODULE['module_system_git_menu_admin'] = 'Admin';
