<?php

// Translation of menu file /home/dennis/www/coscms/modules/module_system_git/menu.inc

$_COS_LANG_MODULE['Modules'] = 'Modules';

$_COS_LANG_MODULE['module_system_git_menu_list'] = 'List Modules';
// Translation of menu file /home/dennis/www/coscms/modules/module_system_git/user/menu.inc

$_COS_LANG_MODULE['module_system_git_menu_user_list'] = 'List Your Modules';

$_COS_LANG_MODULE['module_system_git_menu_user'] = 'Your Modules';
$_COS_LANG_MODULE['module_system_git_menu_add'] = 'Add New Module';


