<?php

$_COS_LANG_MODULE['module_system_git_menu_admin_list'] = 'Skjulte moduler';
$_COS_LANG_MODULE['Modules'] = 'Moduler';
$_COS_LANG_MODULE['module_system_git_menu_user_list'] = 'Liste din Moduler';
$_COS_LANG_MODULE['module_system_git_menu_add'] = 'Ny modul';
$_COS_LANG_MODULE['module_system_git_menu_list'] = 'List Moduler';
$_COS_LANG_MODULE['module_system_git_menu_user'] = 'Dine Moduler';
$_COS_LANG_MODULE['module_system_git_menu_admin'] = 'Admin';
