<?php

$_COS_LANG_MODULE['module_system_git_menu_admin_list'] = 'Versteckte Module';
$_COS_LANG_MODULE['Modules'] = 'Module';
$_COS_LANG_MODULE['module_system_git_menu_user_list'] = 'Liste Ihre Module';
$_COS_LANG_MODULE['module_system_git_menu_add'] = 'Neues Modul hinzufügen';
$_COS_LANG_MODULE['module_system_git_menu_list'] = 'Liste Module';
$_COS_LANG_MODULE['module_system_git_menu_user'] = 'Ihre Module';
$_COS_LANG_MODULE['module_system_git_menu_admin'] = 'Admin';
