<?php

$_COS_LANG_MODULE['module_system_git_menu_admin_list'] = 'Hidden Moduulit';
$_COS_LANG_MODULE['Modules'] = 'Moduulit';
$_COS_LANG_MODULE['module_system_git_menu_user_list'] = 'Listaa Moduulit';
$_COS_LANG_MODULE['module_system_git_menu_add'] = 'Lisää uusi moduuli';
$_COS_LANG_MODULE['module_system_git_menu_list'] = 'Lista Moduulit';
$_COS_LANG_MODULE['module_system_git_menu_user'] = 'Moduulien';
$_COS_LANG_MODULE['module_system_git_menu_admin'] = 'Admin';
