<?php

$_COS_LANG_MODULE['Modules'] = 'Moduler';
$_COS_LANG_MODULE['module_system_git_menu_list'] = 'List Moduler';
$_COS_LANG_MODULE['module_system_git_menu_user_list'] = 'Lista dina moduler';
$_COS_LANG_MODULE['module_system_git_menu_user'] = 'Dina Moduler';
$_COS_LANG_MODULE['module_system_git_menu_add'] = 'Lägg till ny modul';
$_COS_LANG_MODULE['module_system_git_menu_admin'] = 'Admin';
$_COS_LANG_MODULE['module_system_git_menu_admin_list'] = 'Hidden Moduler';
